services:
  react:
    container_name: react
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app
    command: sh -c "cd react-app && yarn start" 
    ports:
      - 3000:3000
    stdin_open: true

  tests:
    container_name: react-test
    build:
      context: .
      dockerfile: dockerfile.test
    volumes:
      - type: bind
        source: ./test
        target: /test
    command: pytest -s /test/test_playwright.py
    depends_on:
      - react
    stdin_open: true