services:
  gfarm-http-gateway:
    build:
      context: .
    container_name: gfarm-http-gateway
    command: --host 0.0.0.0 --port 8080 --root-path /main --forwarded-allow-ips="*"
    volumes:
      # Required: Gfarm HTTP gateway config
      - ./gfarm-http-gateway-for-HPCI-dev.conf:/config/gfarm-http-gateway.conf:ro
      # Required: Gfarm config
      - ./config/gfarm2.conf:/config/gfarm2.conf:ro
      # Required: CA certs for Gfarm
      - ./config/certs:/config/certs:ro
      # Custom Login Page
      - ./templates/login-idp-switch-dev.html:/config/templates/login.html
    depends_on:
      - redis
    restart: unless-stopped

  gfarm-http-gateway-sub:
    build:
      context: .
    container_name: gfarm-http-gateway-sub
    command: --host 0.0.0.0 --port 8080 --root-path /sub --forwarded-allow-ips="*"
    volumes:
      # Required: Gfarm HTTP gateway config
      - ./gfarm-http-gateway-for-HPCI-dev-sub.conf:/config/gfarm-http-gateway.conf:ro
      # Required: Gfarm config
      - ./config/gfarm2.conf:/config/gfarm2.conf:ro
      # Required: CA certs for Gfarm
      - ./config/certs:/config/certs:ro
      # Custom Login Page
      - ./templates/login-idp-switch-dev.html:/config/templates/login.html
    depends_on:
      - redis
    restart: unless-stopped

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "8080:8080"  # HTTP (development only)
    volumes:
      # Required: Nginx config
      - ./nginx-for-HPCI-dev-with-sub.conf:/etc/nginx/conf.d/gfarm.conf:ro
    depends_on:
      - gfarm-http-gateway
      - gfarm-http-gateway-sub
    restart: unless-stopped

  redis:
    image: redis
    command: ["redis-server", "/config/redis.conf"]
    volumes:
      # Required: Redis configuration
      - ./redis.conf.sample:/config/redis.conf:ro
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  redis-data: