services:
  gfarm-http-gateway:
    build:
      context: .
    container_name: gfarm-http-gateway
    command: --host 0.0.0.0 --port 8080
    # for Run with a Subpath
    # command: --host 0.0.0.0 --port 8080 --root-path /gfarm
    volumes:
      # Required: Gfarm HTTP gateway config
      - ./gfarm-http-gateway-for-HPCI.conf:/config/gfarm-http-gateway.conf:ro
      # Required: Gfarm config
      - ./config/gfarm2.conf:/config/gfarm2.conf:ro
      # Required: CA certs for Gfarm
      - ./config/certs:/config/certs:ro
    ports:
          - "127.0.0.1:8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis
    command: ["redis-server", "/config/redis.conf"]
    volumes:
      # Required: Redis configuration
      - ./redis/redis.conf:/config/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped
