services:
  gfarm-http-gateway:
    build:
      context: .
      dockerfile: Dockerfile-for-HPCI
    container_name: gfarm-http-gateway
    command: --host 0.0.0.0 --port 8080
    # for Run with a Subpath
    # command: --host 0.0.0.0 --port 8000 --root-path /gfarm
    volumes:
      # Required: Gfarm HTTP gateway config
      - ./gfarm-http-gateway-for-HPCI.conf:/config/gfarm-http-gateway.conf:ro
    ports:
          - "127.0.0.1:8080:8080"
    restart: unless-stopped

