name: Test gfarm-http-gateway

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ./venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Make setup
        run: make setup
      - name: Make test
        run: make test
      - name: Make flake8
        run: make flake8
